version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/generated_images:/app/generated_images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # 컨테이너가 항상 재시작되도록 설정
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    # backend 서비스가 시작된 후에 frontend가 시작되도록 설정
    depends_on:
      - backend
    restart: always
